apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MMDBadCoder/k8s-argo-quickstart
    targetRevision: main
    path: manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
